### ISSUE TITLE
EK Quantum Delta² TEC Not Showing on Home Screen

### ISSUE THREAD

**Issue by d-mccoy** [juvgrfunex/cryo-cooler-controller#1]
I have a working EK Quantum Delta² TEC on a 13900K. Attempting to run cryo_cooler_controller.exe shows a singular "COM 3" which returns "Error connecting to Port COM3 (Access is denied.)". A second "COM 3" showed up after unplugging/replugging the USB on the cooler. Same response if I attempt to use the second COM 3 port.

**Comment by juvgrfunex** [comment]
Hi, do you have the official software installed?
Unfortunately it is not possible for both of them to work at the same time.

**Comment by d-mccoy** [comment]
Ah! Good to know! Might be worth adding to the readme for future users. BTW - thank you SO MUCH for this project. The Intel TEC coolers are pretty sweet, lame that they're tied to specific SKUs. My future goals include designing an LGA1700 > AM5 adapter for Ryzen usage.

After uninstalling and rebooting I now get the following when attempting to Connect (COM3 is the only port listed still):

Error connecting to Port COM3 (Tecstatus bit pattern invalid: 111011100000010011111)

**Comment by juvgrfunex** [comment]
> Ah! Good to know! Might be worth adding to the readme for future users. 

Good idea!

> After uninstalling and rebooting I now get the following when attempting to Connect (COM3 is the only port listed still):
> 
> Error connecting to Port COM3 (Tecstatus bit pattern invalid: 111011100000010011111)

Looks like there are 3 extra flags set which i have not seen before. I only have the cooler master version to test with so maybe these only exist on the delta2.
I have created a version that ignores the extra flags here: https://github.com/juvgrfunex/cryo-cooler-controller/releases/tag/v1.0.2-beta1
Can you please try what happens when you use that?

**Comment by d-mccoy** [comment]
Progress!

I can Connect and get the TEC to work! Only issue is that it doesn't reliably open, sometimes after clicking Connect it'll load up the main window for a couple frames and then close out.

**Comment by juvgrfunex** [comment]
> Progress!

Great!

> I can Connect and get the TEC to work! Only issue is that it doesn't reliably open, sometimes after clicking Connect it'll load up the main window for a couple frames and then close out.

I believe this is a bug that happens when you try to hover a point but there is no data yet. I though i had fixed that before but i guess i didn't.
I looked at it again and hopefully this update fixes it for good:
https://github.com/juvgrfunex/cryo-cooler-controller/releases/tag/v1.0.2-beta2

By the way, could you tell me what firmware and hardware version it shows on your cooler?

**Comment by d-mccoy** [comment]
Looks to have solved it! 10/10 attempts connected properly

Firmware:
28.B1

Hardware:
1900546

Cheers

**Comment by juvgrfunex** [comment]
Changes released with [v1.0.2](https://github.com/juvgrfunex/cryo-cooler-controller/releases/tag/v1.0.2)
